version: '3.9'
services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rm00
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7.7
    restart: always
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: 1qaz2wsx
      DOCKER_INFLUXDB_INIT_ORG: rm00
      DOCKER_INFLUXDB_INIT_BUCKET: rm00
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 123456
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
